#!/bin/bash

set -e

dockerCmd="docker compose"
if (( $# == 2 )); then
    dockerCmd="docker-compose"
fi

if (( $# < 1 )); then
    echo "Illegal number of parameters"
    echo "usage: services [create|start|stop]"
    exit 1
fi


stoppingContainers () {
	export $(cat .env | grep "#" -v)
	echo "Stopping running containers"
	${dockerCmd} -f multiple.yml down -v --remove-orphans

	echo "Removing HDFS files"
	for dir in ./docker-compose/data/*; do
		[ "$dir" = "./docker-compose/data" ] && continue
		rm -rf "$dir"
	done
}

command="$1"
case "${command}" in
	"help")
		echo "usage: services [create|start|stop]"
		;;
	"stop")
		stoppingContainers
		;;
	"start")
		echo -e "Starting containers: \033[1;34mOrion\033[0m, \033[1;34mCygnus\033[0m, \033[1;36mIoT-Agent\033[0m, \033[1mMongoDB\033[0m, \033[1mMySQL\033[0m"
		${dockerCmd} -f multiple.yml up -d --remove-orphans
		;;
	"create")
		export $(cat .env | grep "#" -v)
		echo "Pulling Docker images"
		docker pull curlimages/curl
		${dockerCmd} -f multiple.yml  pull
		;;
	*)
		echo "Command not Found."
		echo "usage: services [create|multiple|stop]"
		exit 127;
		;;
esac
